max_epochs: 100
accelerator: gpu
devices: 1 #8
strategy: "auto" #"ddp"
logger: true
enable_checkpointing: true
enable_model_summary: false
num_sanity_val_steps: 0
# check_val_every_n_epoch: 10
gradient_clip_val: 1.0